[profile.default]
src = "src"
out = "out"
libs = ["lib"]
#evm_version = "shanghai"
solc = "0.8.13"
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read-write", path = "./script/vmreadwritefile" },

]
bytecode_hash = "none"
cbor_metadata = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
